main: me.foxley.animation.Animation
name: Animation
version: 1.0
author: Foxley
commands:
  heal:
    description: Heal a player
    usage: "§cUtilisation : /<command> [Joueur]"
    permission: animation.command.heal
  tphere:
    description: Teleport a player on you
    usage: "§cUtilisation : /<command> <Joueur>"
    permission: animation.command.tphere
  fly:
    description: Enable the fly
    usage: "§cUtilisation : /<command> <Joueur>"
    permission: animation.command.fly